<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Jev.Sdk.Sample</RootNamespace>
    <AssemblyName>Jev.Sdk.Sample</AssemblyName>
    <IsPackable>false</IsPackable>
    <Description>A minimal console client for the Jev.Sdk library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Jev.Sdk/Jev.Sdk.csproj" />
    <ProjectReference Include="../../src/Jev.Sdk.DependencyInjection/Jev.Sdk.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
